"""empty message

Revision ID: 0c60cf68a004
Revises: f72e61bdd104
Create Date: 2022-01-05 15:19:26.761581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c60cf68a004'
down_revision = 'f72e61bdd104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friend_requests_user_id_to_fkey', 'friend_requests', type_='foreignkey')
    op.drop_constraint('friend_requests_user_id_from_fkey', 'friend_requests', type_='foreignkey')
    op.drop_column('friend_requests', 'user_id_to')
    op.drop_column('friend_requests', 'user_id_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('user_id_from', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friend_requests', sa.Column('user_id_to', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('friend_requests_user_id_from_fkey', 'friend_requests', 'users', ['user_id_from'], ['id'])
    op.create_foreign_key('friend_requests_user_id_to_fkey', 'friend_requests', 'users', ['user_id_to'], ['id'])
    # ### end Alembic commands ###
