"""empty message

Revision ID: 145e74346817
Revises: bf2578c077af
Create Date: 2022-11-03 08:15:53.216741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145e74346817'
down_revision = 'bf2578c077af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_from', sa.Integer(), nullable=False),
    sa.Column('user_id_to', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
