"""empty message

Revision ID: 309363f673e8
Revises: 45c9de43d428
Create Date: 2021-11-22 10:05:13.755492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309363f673e8'
down_revision = '45c9de43d428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breed_traits', sa.Column('question', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breed_traits', 'question')
    # ### end Alembic commands ###
