"""empty message

Revision ID: 40cc94893c67
Revises: dd04435c2098
Create Date: 2021-11-16 13:41:21.409528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cc94893c67'
down_revision = 'dd04435c2098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('breed_group', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'breeds', 'breed_groups', ['breed_group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breeds', type_='foreignkey')
    op.drop_column('breeds', 'breed_group')
    # ### end Alembic commands ###
