"""empty message

Revision ID: 45c9de43d428
Revises: d2bc612233b0
Create Date: 2021-11-20 18:14:38.457921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c9de43d428'
down_revision = 'd2bc612233b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('breed_video', sa.String(), nullable=False))
    op.create_foreign_key(None, 'posts', 'breed_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('breeds', 'breed_video')
    # ### end Alembic commands ###
