"""empty message

Revision ID: 96a2f86ec4c7
Revises: 40cc94893c67
Create Date: 2021-11-16 13:44:05.476929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a2f86ec4c7'
down_revision = '40cc94893c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breed_answers', sa.Column('breed_id', sa.Integer(), nullable=False))
    op.drop_constraint('breed_answers_user_id_fkey', 'breed_answers', type_='foreignkey')
    op.create_foreign_key(None, 'breed_answers', 'breeds', ['breed_id'], ['id'])
    op.drop_column('breed_answers', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breed_answers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'breed_answers', type_='foreignkey')
    op.create_foreign_key('breed_answers_user_id_fkey', 'breed_answers', 'users', ['user_id'], ['id'])
    op.drop_column('breed_answers', 'breed_id')
    # ### end Alembic commands ###
