"""empty message

Revision ID: bf2578c077af
Revises: 0c60cf68a004
Create Date: 2022-01-05 15:21:09.494928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2578c077af'
down_revision = '0c60cf68a004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('user_id_from', sa.Integer(), nullable=False))
    op.add_column('friend_requests', sa.Column('user_id_to', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'friend_requests', 'users', ['user_id_to'], ['id'])
    op.create_foreign_key(None, 'friend_requests', 'users', ['user_id_from'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.drop_column('friend_requests', 'user_id_to')
    op.drop_column('friend_requests', 'user_id_from')
    # ### end Alembic commands ###
