"""empty message

Revision ID: cb85a9bda95c
Revises: 96a2f86ec4c7
Create Date: 2021-11-16 14:24:26.609621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb85a9bda95c'
down_revision = '96a2f86ec4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###
