"""empty message

Revision ID: dd04435c2098
Revises: 69901eb5cbb7
Create Date: 2021-11-16 13:07:04.836191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd04435c2098'
down_revision = '69901eb5cbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('breeds_breed_group_fkey', 'breeds', type_='foreignkey')
    op.drop_column('breeds', 'breed_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('breed_group', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('breeds_breed_group_fkey', 'breeds', 'breed_groups', ['breed_group'], ['id'])
    # ### end Alembic commands ###
