"""empty message

Revision ID: f72e61bdd104
Revises: fc390be10fc4
Create Date: 2022-01-05 14:56:10.283105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72e61bdd104'
down_revision = 'fc390be10fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_from', sa.Integer(), nullable=False),
    sa.Column('user_id_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_user_id', sa.Integer(), nullable=False),
    sa.Column('friend_user_id', sa.Integer(), nullable=False),
    sa.Column('is_following', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends_list')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
